---
- name: Import Playbook 00_provision.yaml
  ansible.builtin.import_playbook: playbooks/00_provision.yaml

- name: Import Playbook 01_alb_setup.yaml
  ansible.builtin.import_playbook: playbooks/01_alb_setup.yaml

- name: Import Playbook 02_build_inventory.yaml
  ansible.builtin.import_playbook: playbooks/02_build_inventory.yaml

- name: Import Playbook 03_custom_cluster_config.yaml
  ansible.builtin.import_playbook: playbooks/03_custom_cluster_config.yaml